### ISSUE TITLE
Error: Constructs are already initialized: this should not happen

### ISSUE THREAD

**Issue by mondaini** [getlift/lift#142]
Hello. What should we do in those cases?

This is a new service. I've done a couple of deployments but It stopped working and I can't find the reason.

I've tried
* Removing `node_modules` and reinstalling the dependencies using `npm install`
* Reinstalling the serverless-lift plugin
* Removing the service using `serverless remove`

Thank you for your work on this.

```
 Do you want to deploy your project? Yes
 
 Error ---------------------------------------------------
 
  Error: Constructs are already initialized: this should not happen
      at _LiftPlugin.loadConstructs (/home/filipe/projects/pdf-processor/node_modules/serverless-lift/dist/src/plugin.js:175:13)
      at initialize (/home/filipe/projects/pdf-processor/node_modules/serverless-lift/dist/src/plugin.js:92:14)
      at PluginManager.run (/home/filipe/.nvm/versions/node/v16.13.0/lib/node_modules/serverless/lib/classes/PluginManager.js:648:65)
      at async PluginManager.runHooks (/home/filipe/.nvm/versions/node/v16.13.0/lib/node_modules/serverless/lib/classes/PluginManager.js:573:35)
      at async PluginManager.invoke (/home/filipe/.nvm/versions/node/v16.13.0/lib/node_modules/serverless/lib/classes/PluginManager.js:612:9)
      at async PluginManager.spawn (/home/filipe/.nvm/versions/node/v16.13.0/lib/node_modules/serverless/lib/classes/PluginManager.js:635:5)
      at async before:deploy:deploy (/home/filipe/.nvm/versions/node/v16.13.0/lib/node_modules/serverless/lib/plugins/deploy.js:65:11)
      at async PluginManager.runHooks (/home/filipe/.nvm/versions/node/v16.13.0/lib/node_modules/serverless/lib/classes/PluginManager.js:573:35)
      at async PluginManager.invoke (/home/filipe/.nvm/versions/node/v16.13.0/lib/node_modules/serverless/lib/classes/PluginManager.js:610:9)
      at async PluginManager.run (/home/filipe/.nvm/versions/node/v16.13.0/lib/node_modules/serverless/lib/classes/PluginManager.js:672:7)
      at async Serverless.run (/home/filipe/.nvm/versions/node/v16.13.0/lib/node_modules/serverless/lib/Serverless.js:468:5)
      at async /home/filipe/.nvm/versions/node/v16.13.0/lib/node_modules/serverless/lib/cli/interactive-setup/deploy.js:199:13
      at async Object.run (/home/filipe/.nvm/versions/node/v16.13.0/lib/node_modules/serverless/lib/cli/interactive-setup/deploy.js:188:9)
      at async module.exports (/home/filipe/.nvm/versions/node/v16.13.0/lib/node_modules/serverless/lib/cli/interactive-setup/index.js:56:7)
      at async /home/filipe/.nvm/versions/node/v16.13.0/lib/node_modules/serverless/scripts/serverless.js:526:24
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              16.13.0
     Framework Version:         2.66.2
     Plugin Version:            5.5.1
     SDK Version:               4.3.0
     Components Version:        3.18.1
 
Serverless: [AWS sts 200 0.891s 0 retries] getCallerIdentity({})
```

**Comment by mnapoli** [comment]
Ohh that should never happen indeed 😄 

It seems you ran into that problem with the `serverless` command, is that correct? You started a new (empty) project? Which template was this? Any extra information to reproduce could help here.

**Comment by mondaini** [comment]
Hi @mnapoli 

I'm using this template: https://www.serverless.com/examples/aws-python-sqs-worker

Idk if this is related to this issue, but when I run `sls help` I've noticed some command help descriptions as `undefined`

Thanks again for your help :)

```
Commands by plugin

_LiftPlugin
lift .......................... undefined
lift eject .................... Eject Lift constructs to raw CloudFormation
jobs:logs ..................... Output the logs of the queue's worker function
jobs:send ..................... Send a new message to the SQS queue
jobs:failed ................... List failed messages from the dead letter queue
jobs:failed:purge ............. Purge failed messages from the dead letter queue
jobs:failed:retry ............. Retry failed messages from the dead letter queue by moving them to the main queue

ServerlessPythonRequirements
requirements clean ............ Remove .requirements and requirements.zip
requirements install .......... install requirements manually
requirements cleanCache ....... Removes all items in the pip download/static cache (if present)

SsmFetch
serverless-ssm-fetch .......... undefined
serverless-ssm-fetch parameter  Internal use only!
```

**Comment by mondaini** [comment]
@mnapoli, I've found the issue. It started after installing the `serverless-ssm-fetch` plugin. I believe this plugin was initializing the constructs before Lift.

I've removed the ssm-fetch plugin, and things got back working!

**Comment by t-richard** [comment]
Thanks for reporting back @mondaini :+1: 

Note that plugins order does matter in the serverless framework, so maybe moving this plugin below Lift would solve the issue.
